// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2yKL_wdn3tkOkjAbexvJEp6nECn5rj1M',
    appId: '1:544697004384:web:621dc9faa144738293ae05',
    messagingSenderId: '544697004384',
    projectId: 'luyendethithpt',
    authDomain: 'luyendethithpt.firebaseapp.com',
    storageBucket: 'luyendethithpt.firebasestorage.app',
    measurementId: 'G-Y2KBV34DPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4L0Ia6GDaQCZtUi8jVJgwqScGyWzBGgg',
    appId: '1:544697004384:android:caf3ab6df79c1ba993ae05',
    messagingSenderId: '544697004384',
    projectId: 'luyendethithpt',
    storageBucket: 'luyendethithpt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhunzMKx17mtu532Lroy7HoO-7MfwNNr8',
    appId: '1:544697004384:ios:9389e0f7738da0be93ae05',
    messagingSenderId: '544697004384',
    projectId: 'luyendethithpt',
    storageBucket: 'luyendethithpt.firebasestorage.app',
    iosBundleId: 'com.example.appLuyenDeThpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhunzMKx17mtu532Lroy7HoO-7MfwNNr8',
    appId: '1:544697004384:ios:9389e0f7738da0be93ae05',
    messagingSenderId: '544697004384',
    projectId: 'luyendethithpt',
    storageBucket: 'luyendethithpt.firebasestorage.app',
    iosBundleId: 'com.example.appLuyenDeThpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2yKL_wdn3tkOkjAbexvJEp6nECn5rj1M',
    appId: '1:544697004384:web:c48a2ef5bab4bbeb93ae05',
    messagingSenderId: '544697004384',
    projectId: 'luyendethithpt',
    authDomain: 'luyendethithpt.firebaseapp.com',
    storageBucket: 'luyendethithpt.firebasestorage.app',
    measurementId: 'G-W00YDBBB5Z',
  );
}
